import type { InsightReport, Product, ProductReview } from "@/lib/types";

export const products: Product[] = [
  {
    id: "coupang-folding-cart",
    platform: "Coupang",
    url: "https://www.coupang.com/",
    image: "https://images.unsplash.com/photo-1591375372226-3531cf2eb6e9?auto=format&fit=crop&w=900&q=80",
    name: "折叠式静音购物推车 45L",
    brand: "Living Mate",
    category: "家居收纳",
    price: 39900,
    discountPrice: 29900,
    estimatedMonthlySales: 8600,
    reviewCount: 4832,
    rating: 4.7,
    rank: 3,
    favorites: 18200,
    deliveryType: "Rocket Delivery",
    sellerType: "品牌直营",
    size: "45L / 折叠后 12cm",
    colors: ["Cream", "Olive", "Black"],
    material: "ABS + 铝合金拉杆",
    weight: "2.4kg",
    packageSize: "46 x 42 x 13cm",
    sellingPoints: ["一秒折叠", "静音轮", "可坐式上盖", "玄关收纳"],
    keywords: ["购物车", "折叠推车", "露营收纳", "买菜车"],
    collectedAt: "2026-06-14",
    status: "可开发",
    bookmarked: true,
    decision: "强烈建议开发",
    score: 88,
    marginScore: 74,
    riskScore: 28,
  },
  {
    id: "naver-desk-organizer",
    platform: "Naver Shopping",
    url: "https://shopping.naver.com/",
    image: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&w=900&q=80",
    name: "模块化桌面电线收纳盒",
    brand: "Desk On",
    category: "办公整理",
    price: 24900,
    discountPrice: 18900,
    estimatedMonthlySales: 5200,
    reviewCount: 1914,
    rating: 4.6,
    rank: 8,
    favorites: 9400,
    deliveryType: "오늘출발",
    sellerType: "中小品牌",
    size: "32 x 12 x 11cm",
    colors: ["White", "Gray"],
    material: "阻燃 PP",
    weight: "0.8kg",
    packageSize: "34 x 14 x 13cm",
    sellingPoints: ["插线板隐藏", "磁吸盖", "可叠加", "极简桌面"],
    keywords: ["电线收纳", "桌面整理", "插线板盒", "办公室"],
    collectedAt: "2026-06-13",
    status: "已分析",
    bookmarked: false,
    decision: "可以测试",
    score: 79,
    marginScore: 68,
    riskScore: 34,
  },
  {
    id: "ohou-air-fryer-paper",
    platform: "오늘의집",
    url: "https://ohou.se/",
    image: "https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&w=900&q=80",
    name: "空气炸锅硅油纸托 100枚",
    brand: "Kitchen Daily",
    category: "厨房消耗品",
    price: 12900,
    discountPrice: 8900,
    estimatedMonthlySales: 14300,
    reviewCount: 7820,
    rating: 4.5,
    rank: 1,
    favorites: 26800,
    deliveryType: "普通配送",
    sellerType: "贸易商",
    size: "16cm / 20cm",
    colors: ["Natural"],
    material: "食品级硅油纸",
    weight: "0.3kg",
    packageSize: "22 x 22 x 5cm",
    sellingPoints: ["免清洗", "不粘锅", "多尺寸", "高频复购"],
    keywords: ["空气炸锅纸", "厨房纸托", "烘焙纸", "消耗品"],
    collectedAt: "2026-06-12",
    status: "观察中",
    bookmarked: true,
    decision: "继续观察",
    score: 72,
    marginScore: 51,
    riskScore: 47,
  },
  {
    id: "gmarket-neck-fan",
    platform: "Gmarket",
    url: "https://www.gmarket.co.kr/",
    image: "https://images.unsplash.com/photo-1565084888279-aca607ecce0c?auto=format&fit=crop&w=900&q=80",
    name: "无叶挂脖风扇 Pro",
    brand: "Coolit",
    category: "季节家电",
    price: 59900,
    discountPrice: 34900,
    estimatedMonthlySales: 9700,
    reviewCount: 3140,
    rating: 4.1,
    rank: 5,
    favorites: 12100,
    deliveryType: "스마일배송",
    sellerType: "一般卖家",
    size: "均码",
    colors: ["White", "Navy", "Mint"],
    material: "ABS + 电池",
    weight: "0.26kg",
    packageSize: "21 x 19 x 6cm",
    sellingPoints: ["无叶安全", "三档风量", "轻量化", "夏季通勤"],
    keywords: ["挂脖风扇", "夏季用品", "便携风扇", "无叶风扇"],
    collectedAt: "2026-06-11",
    status: "不建议做",
    bookmarked: false,
    decision: "不建议开发",
    score: 58,
    marginScore: 62,
    riskScore: 78,
  },
  {
    id: "coupang-honeycomb-blind",
    platform: "Coupang",
    url: "https://www.coupang.com/",
    image: "https://images.unsplash.com/photo-1560448204-603b3fc33ddc?auto=format&fit=crop&w=900&q=80",
    name: "免打孔蜂巢帘遮光款",
    brand: "Window Fit",
    category: "窗饰",
    price: 45900,
    discountPrice: 32900,
    estimatedMonthlySales: 6400,
    reviewCount: 2260,
    rating: 4.4,
    rank: 4,
    favorites: 15600,
    deliveryType: "Rocket Delivery",
    sellerType: "品牌直营",
    size: "60 x 150cm / 90 x 180cm",
    colors: ["White", "Cream", "Gray"],
    material: "Non-woven fabric + aluminum rail",
    weight: "1.1kg",
    packageSize: "95 x 8 x 8cm",
    sellingPoints: ["免打孔安装", "遮光隔热", "小窗适配", "可裁剪"],
    keywords: ["蜂巢帘", "窗帘", "遮光帘", "honeycomb blind"],
    collectedAt: "2026-06-15",
    status: "可开发",
    bookmarked: true,
    decision: "可以测试",
    score: 81,
    marginScore: 70,
    riskScore: 38,
  },
];

export const mockReviews: ProductReview[] = [
  {
    id: "r1",
    productId: "coupang-folding-cart",
    rating: 5,
    text: "轮子很安静，折叠后尺寸刚好放玄关，买菜搬水很方便。",
    language: "zh",
    createdAt: "2026-06-13",
    source: "Coupang",
  },
  {
    id: "r2",
    productId: "coupang-folding-cart",
    rating: 2,
    text: "拉杆有点松动，装重物的时候质量感觉不稳定。",
    language: "zh",
    createdAt: "2026-06-13",
    source: "Coupang",
  },
  {
    id: "r3",
    productId: "coupang-folding-cart",
    rating: 2,
    text: "포장 박스가 찌그러져 왔고 바퀴에서 소음이 납니다.",
    language: "ko",
    createdAt: "2026-06-12",
    source: "Coupang",
  },
  {
    id: "r4",
    productId: "coupang-honeycomb-blind",
    rating: 5,
    text: "설치가 쉬워요. 색상도 사진과 거의 같고 작은 창문에 잘 맞아요.",
    language: "ko",
    createdAt: "2026-06-15",
    source: "Coupang",
  },
  {
    id: "r5",
    productId: "coupang-honeycomb-blind",
    rating: 2,
    text: "사이즈가 애매해서 창문에 맞지 않아요. 설명서가 더 자세했으면 좋겠어요.",
    language: "ko",
    createdAt: "2026-06-15",
    source: "Coupang",
  },
  {
    id: "r6",
    productId: "coupang-honeycomb-blind",
    rating: 3,
    text: "颜色比照片偏灰，建议增加实拍图。安装不难但说明书太简单。",
    language: "zh",
    createdAt: "2026-06-14",
    source: "Coupang",
  },
];

export const reports: Record<string, InsightReport> = {
  "coupang-folding-cart": {
    productId: "coupang-folding-cart",
    salesAnalysis: {
      whySelling: ["解决无车家庭搬运痛点", "折叠厚度适合韩国小户型玄关", "Rocket 配送降低决策成本"],
      priceAdvantage: "主力价格落在 29,900 KRW，低于同容量竞品约 12%-18%。",
      salesTrend: "近 30 天收藏和评论增速稳定，非短期冲榜。",
      seasonality: "春夏露营会放大需求，但买菜、搬水、收纳属于全年需求。",
      demandType: "长期需求产品，适合做差异化升级款。",
    },
    competitorAdvantages: {
      title: "标题同时覆盖购物、露营、收纳三类搜索意图。",
      mainImage: "主图直接展示折叠前后对比，用户一眼理解体积优势。",
      detailPage: "详情页用真实户型场景解释玄关收纳和电梯搬运。",
      function: "静音轮、坐盖和拉杆高度是核心转化点。",
      size: "45L 容量刚好覆盖日常买菜和露营轻搬运。",
      color: "奶油色与橄榄色更接近韩国家居审美。",
      brand: "品牌感不强，给新品牌切入空间。",
      delivery: "Rocket Delivery 是明显优势，测试期需用本地仓或快速配送对冲。",
    },
    reviewAnalysis: {
      likes: ["轮子安静", "折叠后不占地方", "能装大瓶水和大米", "颜色不像传统买菜车"],
      dislikes: ["重物时拉杆晃动", "上盖承重描述不清", "轮子卡头发", "包装盒破损"],
      purchaseReasons: ["无车购物", "父母使用", "露营装备搬运", "小户型收纳"],
      returnReasons: ["尺寸比想象大", "轮子异响", "拉杆松动", "承重期待过高"],
    },
    aiSummary: {
      worthDoing: "值得做，但不要做同款低价复制。",
      why: "需求明确、评论量健康、差评集中在可工程优化点。",
      biggestOpportunity: "做更稳定拉杆、更清晰承重说明和更高级配色。",
      biggestRisk: "体积品物流成本高，且 Rocket 配送竞品会压缩转化。",
      suggestedPurchaseQty: "首批 300-500 件，分 2 色测试。",
      suggestedTestMethod: "Coupang + Naver 双平台，以 34,900 KRW 测试升级款接受度。",
      finalDecision: "强烈建议开发",
    },
    developmentAdvice: {
      positioning: "小户型家庭的高级折叠搬运车，不是老人买菜车。",
      productChanges: ["拉杆加厚并做晃动测试", "轮组改为可拆清洁结构", "上盖承重标注真实测试值"],
      packaging: ["外箱加护角", "主图贴纸强调折叠厚度", "内附韩文快速安装卡"],
      contentStrategy: ["拍摄玄关收纳场景", "展示 2L 水 6 瓶装载", "对比传统购物车外观"],
      supplierQuestions: ["轮子噪音分贝测试是多少", "拉杆循环测试次数", "单箱材积和破损率", "是否可做韩文模具标识"],
    },
    riskChecklist: [
      { level: "中", title: "物流体积成本", mitigation: "优先谈压缩包装和韩国本地 3PL 价格。" },
      { level: "中", title: "承重投诉", mitigation: "详情页写清动态承重与静态承重。" },
      { level: "低", title: "外观同质化", mitigation: "用配色、轮组和内容场景做区隔。" },
    ],
  },
};

export const fallbackReport: InsightReport = {
  productId: "fallback",
  salesAnalysis: {
    whySelling: ["搜索需求明确", "价格带适中", "评论样本足够判断真实痛点"],
    priceAdvantage: "需要补充竞品价格带后判断。",
    salesTrend: "建议接入平台更新任务后观察 14-30 天趋势。",
    seasonality: "需结合关键词搜索峰值判断。",
    demandType: "当前判断为可测试需求。",
  },
  competitorAdvantages: {
    title: "标题覆盖核心关键词，但差异化不足。",
    mainImage: "主图需要强化使用场景和尺寸感。",
    detailPage: "详情页应优先回答材质、尺寸、安装和售后。",
    function: "功能需要围绕评论痛点升级。",
    size: "需确认韩国住宅和使用习惯适配。",
    color: "建议先测试白、灰、奶油等低风险配色。",
    brand: "品牌壁垒有限，可用内容和供应链切入。",
    delivery: "配送速度会明显影响转化。",
  },
  reviewAnalysis: {
    likes: ["价格合适", "解决具体场景问题", "使用方便"],
    dislikes: ["质量稳定性", "尺寸预期偏差", "包装保护不足"],
    purchaseReasons: ["即时痛点", "平台推荐", "评论说服"],
    returnReasons: ["实物与预期不符", "破损", "功能没有详情页说得清楚"],
  },
  aiSummary: {
    worthDoing: "可以测试。",
    why: "有需求信号，但还需要评论和供应链验证。",
    biggestOpportunity: "从差评里做微创新，而不是跟卖同款。",
    biggestRisk: "同质化竞争和物流/售后成本。",
    suggestedPurchaseQty: "首批 100-300 件。",
    suggestedTestMethod: "先用 1 个核心平台小批量测标题、主图和价格。",
    finalDecision: "可以测试",
  },
  developmentAdvice: {
    positioning: "围绕明确人群和场景做窄定位。",
    productChanges: ["补齐差评高频问题", "做尺寸和材质差异化", "降低退货误解"],
    packaging: ["加强运输保护", "韩文化说明", "外箱标注规格"],
    contentStrategy: ["主图展示真实尺寸", "详情页回答风险问题", "用对比图解释升级点"],
    supplierQuestions: ["最低起订量", "质检标准", "交期", "可定制范围"],
  },
  riskChecklist: [
    { level: "中", title: "数据不足", mitigation: "补充平台趋势和评论样本。" },
    { level: "中", title: "同质化", mitigation: "只开发能解决差评的版本。" },
  ],
};
